[package]
name = "wipi"
version = "0.0.1"
edition = "2024"

[features]
ktf = ["wipi_types/ktf"]
lgt = ["wipi_types/lgt"]

[dependencies]
cfg-if = { version = "^1.0", default-features = false }

wipi_types = { path = "../wipi_types" }
