[package]
name = "wipic_simulation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wipi_boot = { workspace = true, features = ["simulation"] }
wipi_types = { workspace = true }
