[package]
name = "examples"
version = "0.0.1"
edition = "2024"

[dependencies]
wipi = { path = "../wipi" }

[features]
ktf = ["wipi/ktf"]
lgt = ["wipi/lgt"]

[[bin]]
name = "helloworld"
path = "src/helloworld.rs"

[[bin]]
name = "triangle"
path = "src/triangle.rs"
