[package]
name = "examples"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wipi = { path = "../wipi" }

[features]
ktf = ["wipi/ktf"]
lgt = ["wipi/lgt"]
simulation = ["wipi/simulation"]

[[bin]]
name = "helloworld"
path = "src/helloworld.rs"

[[bin]]
name = "paint"
path = "src/paint.rs"
