[package]
name = "wipi_boot"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
ktf = ["wipi_types/ktf"]
lgt = ["wipi_types/lgt"]

[dependencies]
cfg-if = { workspace = true }

wipi_types = { path = "../wipi_types" }
