[package]
name = "wipi_types"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
ktf = []
lgt = []
simulation = []

[dependencies]
cfg-if = { workspace = true }

bytemuck = { version = "^1.23", default-features = false, features = ["derive"] }
